public class Calculator {
    public static void sum(integer a ,integer b){
        integer sum=a+b;
        System.debug('Sum of the value:' +sum);
    }
    public static void Multiply(integer a ,integer b){
        integer Multi=a*b;
         System.debug('Multiply the value:' +Multi);//My changes
    }
    public static void subtract(integer a ,integer b){
        integer sub=a-b;
         System.debug('Sub of the value:' +sub);
    }
    public static void divide(integer a ,integer b){
        integer div=a/b;
         System.debug('Sum of the value:' +div);
    }
}